### ISSUE TITLE
Update to 1.18

### ISSUE THREAD

**Issue by Greazi-Times** [5uso/SidebarDisplayExample#1]
Hi there,

I have been looking at this recourse and it works great for a 1.17 server but would it be possible to get it to work for 1.18 as well??

Kind regards,
Greazi

**Comment by 5uso** [comment]
Hi, you may want to look at [Ts' version of this.](https://github.com/McTsts/mc-core-shaders/tree/main/hide%20sidebar%20numbers) It should work on 1.18
